source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '6.1'
pod 'TouchJSON'
pod 'AVOSCloud'
pod 'AVOSCloudSNS'
pod 'AFNetworking'
pod 'TouchJSON'
pod 'pop'
pod 'OpenCV'
pod 'SVProgressHUD'
pod 'MBProgressHUD'
pod 'QBImagePickerController'